service: royal-flush

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    LD_LIBRARY_PATH: build/Release

custom:
  src: dist
  functions:
    hello: ${self:custom.src}/handler.hello
    histogram: ${self:custom.src}/handler.histogram

package:
  include:
    - dist/**
    - build/**
    - node_modules/**
  exclude:
    - ./**

functions:
  hello:
    handler: ${self:custom.functions.hello}
    events:
      - http:
          path: api/hello
          method: get
  histogram:
    handler: ${self:custom.functions.histogram}
    events:
      - http:
          path: api/histogram
          method: post

plugins:
  - serverless-offline
