service: royal-flush

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    LD_LIBRARY_PATH: build/Release

custom:
  src: dist/endpoints
  functions:
    hello: ${self:custom.src}/hello.handler
    histogram: ${self:custom.src}/histogram.handler
    odds: ${self:custom.src}/odds.handler

package:
  include:
    - dist/**
    - build/**
    - node_modules/**
  exclude:
    - ./**

functions:
  hello:
    handler: ${self:custom.functions.hello}
    events:
      - http:
          path: api/hello
          method: get
          cors: true
  histogram:
    handler: ${self:custom.functions.histogram}
    events:
      - http:
          path: api/histogram
          method: post
          cors: true
  odds:
    handler: ${self:custom.functions.odds}
    events:
      - http:
          path: api/odds
          method: post
          cors: true

plugins:
  - serverless-offline
