# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: jasminder88/royal_flush_amazonlinux:latest
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      

      - run:
          name: 'submodules'
          command: |
            git submodule init
            git submodule update --remote
      
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: 'node commands'
          command: |
            source /root/.nvm/nvm.sh
            nvm use 8.10.0
            npm run build-nit
            npm install
            npm test

      - save_cache:
          paths:
            - node_modules
            - nit/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
